<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hy</string>
	</array>
	<key>name</key>
	<string>hydra</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>keywords like from 0 to 10 do...</string>
			<key>match</key>
			<string>[spawn|if|else|then|for|while|do|not|and|or|from|to|by|function|end|module|class|import|export|super|this|return]\s+</string>
			<key>name</key>
			<string>keyword.source.hydra</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hydra</string>
	<key>uuid</key>
	<string>bc954012-51f2-4fb7-af12-34819861d560</string>
</dict>
</plist>
